name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, gd, fileinfo
          coverage: none

      - name: Validate PHP syntax
        run: |
          find . -name "*.php" -exec php -l {} \; | grep -v "No syntax errors"

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          ssh_private_key: ${{ secrets.SFTP_SSH_KEY }}
          local_path: './*'
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
          sftp_only: true
          args: '--exclude=.git --exclude=.github --exclude=uploads --exclude=build --exclude=config.php'

      - name: Set permissions via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_SSH_KEY }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          script: |
            cd ${{ secrets.SFTP_REMOTE_PATH }}
            
            # Vytvoř config.php pokud neexistuje
            if [ ! -f config.php ]; then
              cat > config.php << 'EOF'
            <?php
            declare(strict_types=1);
            
            $UPLOAD_DIR = __DIR__ . '/uploads';
            $MAX_SIZE = 50 * 1024 * 1024;
            
            if (!is_dir($UPLOAD_DIR)) {
                mkdir($UPLOAD_DIR, 0755, true);
            }
            EOF
            fi
            
            mkdir -p uploads
            chmod 755 uploads
            chmod 644 *.php *.css
            chmod 755 .

      - name: Deployment notification
        if: success()
        run: echo "✅ Deployment successful"

      - name: Deployment failed
        if: failure()
        run: echo "❌ Deployment failed"
